Workflows and linters are upgraded. Build configuration is added.

diff --git a/.github/workflows/maven-release-v2.yaml b/.github/workflows/maven-release-v2.yaml
--- a/.github/workflows/maven-release-v2.yaml
+++ b/.github/workflows/maven-release-v2.yaml
@@ -13,13 +13,16 @@
 # - `GITHUB_TOKEN`: The GitHub token used for authentication.
 # - `GPG_PRIVATE_KEY`: The GPG private key used for signing the artifacts.
 # - `GPG_PASSPHRASE`: The passphrase for the GPG private key.
+# - `MAVEN_USER`: The Maven username used for authentication (for Maven Central).
+# - `MAVEN_PASSWORD`: The Maven password used for authentication (for Maven Central).
+# - `GH_BUMP_VERSION_APP_ID`: The GitHub App ID used for authentication.
+# - `GH_BUMP_VERSION_APP_KEY`: The private key for the GitHub App used for authentication.
 # The workflow also requires the https://github.com/Netcracker/.github/blob/main/config/examples/release-drafter-config.yml config file to create a GitHub release.
-# Please prepare project's pom.xml file according to https://github.com/Netcracker/qubership-workflow-hub/blob/main/docs/maven-publish-pom-preparation_doc.md
+# Please prepare project's pom.xml file according to https://github.com/netcracker/qubership-workflow-hub/blob/main/docs/maven-publish-pom-preparation_doc.md
 # to be able to use this workflow.
 
 name: Maven release
 
-description: 'Release Maven artifact and publish to GitHub Packages or Maven Central'
 run-name: ${{ github.event.inputs.version-type }} release for ${{ github.event.repository.name }}
 
 on:
@@ -50,7 +53,7 @@ on:
       build-docker:
         description: 'Build Docker image'
         required: false
-        default: 'false'
+        default: false
         type: boolean
 
 permissions:
@@ -62,9 +65,11 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: "Build and Publish current SNAPSHOT (dry run)"
-        uses: netcracker/qubership-workflow-hub/actions/maven-release@main
+        uses: netcracker/qubership-workflow-hub/actions/maven-release@v1.0.1
         with:
+          java-version: "21"
           version-type: ${{ github.event.inputs.version-type }}
+          ref: ${{ github.ref }}
           module: ${{ github.event.repository.name }}
           maven-args: ${{ inputs.mvn-args }}
           profile: ${{ inputs.profile }}
@@ -82,56 +87,100 @@ jobs:
       release-version: ${{ steps.build-and-publish.outputs.release-version }}
     runs-on: ubuntu-latest
     steps:
+      - name: "Prepare app token"
+        uses: actions/create-github-app-token@v1
+        id: app-token
+        with:
+          app-id: ${{ vars.GH_BUMP_VERSION_APP_ID }}
+          private-key: ${{ secrets.GH_BUMP_VERSION_APP_KEY }}
       - name: "Build and Publish"
         id: build-and-publish
+
         uses: netcracker/qubership-workflow-hub/actions/maven-release@main
         with:
+          java-version: "21"
           version-type: ${{ github.event.inputs.version-type }}
+          ref: ${{ github.ref }}
           module: ${{ github.event.repository.name }}
           maven-args: ${{ inputs.mvn-args }}
           profile: ${{ inputs.profile }}
           server-id: ${{ inputs.profile }}
-          token: ${{ secrets.GITHUB_TOKEN }}
+          token: ${{ steps.app-token.outputs.token }}
           maven-user: ${{ inputs.profile == 'github' && github.actor || secrets.MAVEN_USER }}
           maven-password: ${{ inputs.profile == 'github' && secrets.GITHUB_TOKEN || secrets.MAVEN_PASSWORD }}
           gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
           gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
           dry-run: 'false'
-  check-dockerfile:
-    if: ${{ github.event.inputs.build-docker == 'true' }}
-    runs-on: ubuntu-latest
-    needs: [deploy]
-    outputs:
-      dockerfile_exists: ${{ steps.check_dockerfile.outputs.df_exists }}
-    steps:
-      - uses: actions/checkout@v4
-      - name: "Check Dockerfile existence"
-        id: check_dockerfile
-        shell: bash
-        run: |
-          if [[ -f Dockerfile ]]; then
-            echo "df_exists=exists" >> "$GITHUB_OUTPUT"
-          else
-            echo "Dockerfile does not exist. Docker build stage will be skipped"
-            echo "df_exists=notexists" >> "$GITHUB_OUTPUT"
-          fi
-          echo "GITHUB_OUTPUT:"
-          cat "$GITHUB_OUTPUT"
 
-  docker-build-publish:
-    needs: [deploy, check-dockerfile]
-    if: ${{ github.event.inputs.build-docker == 'true' && needs.check-dockerfile.outputs.dockerfile_exists == 'exists' }}
-    uses: netcracker/qubership-workflow-hub/.github/workflows/docker-publish.yml@main
-    with:
-      ref: "v${{ needs.deploy.outputs.release-version }}"
-      artifact-id: ${{ needs.update-pom-version.outputs.artifact_id }}
-      dry-run: ${{ inputs.dry-run }}
-      download-artifact: true
+      - name: Upload all Maven target directories
+        uses: actions/upload-artifact@v4
+        with:
+          name: qubership-testing-platform-ram
+          path: '**/target'
+
+  load-docker-build-components:
+    needs: [deploy]
+    runs-on: ubuntu-latest
+    outputs:
+      component: ${{ steps.load_component.outputs.components }}
+      platforms: ${{ steps.load_component.outputs.platforms }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Load Docker Configuration
+        id: load_component
+        run:  |
+          verify=$(cat "$GITHUB_WORKSPACE/.github/docker-build-config.json" | jq '
+          def verify_structure:
+          .components as $components
+          | .platforms as $platforms
+          | ($components | type == "array")
+          and (all($components[]; has("name") and has("file") and has("context")))
+          and ($platforms | type == "string");
+          verify_structure
+          | if . then true else false end
+          ')
+          if [ ${verify} == 'true' ]; then
+            echo "✅ $GITHUB_WORKSPACE/.github/docker-build-config.json file is valid"
+            components=$(jq -c ".components" "$GITHUB_WORKSPACE/.github/docker-build-config.json")
+            platforms=$(jq -c ".platforms" "$GITHUB_WORKSPACE/.github/docker-build-config.json")
+          else
+            echo "❗ $GITHUB_WORKSPACE/.github/docker-build-config.json file is invalid"
+            echo "❗ $GITHUB_WORKSPACE/.github/docker-build-config.json file is invalid" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
+          echo "components=${components}" >> $GITHUB_OUTPUT
+          echo "platforms=${platforms}" >> $GITHUB_OUTPUT
+
+  docker-build:
+    permissions:
+      contents: write
+      packages: write
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        component: ${{ fromJson(needs.load-docker-build-components.outputs.component) }}
+    needs: [ load-docker-build-components, deploy ]
+    steps:
+      - name: "Docker Build"
+        id: docker_build
+        uses: netcracker/qubership-workflow-hub/actions/docker-action@main
+        with:
+          ref: v${{ needs.deploy.outputs.release-version }}
+          download-artifact: true
+          download-artifact-path: build-context
+          dry-run: false
+          component: ${{ toJson(matrix.component) }}
+          platforms: ${{ needs.load-docker-build-components.outputs.platforms }}
+        env:
+          GITHUB_TOKEN: ${{ github.token }}
 
   github-release:
-    needs: [deploy, docker-build-publish]
+    needs: [deploy]
     if: ${{ needs.deploy.result == 'success' }}
-    uses: netcracker/qubership-workflow-hub/.github/workflows/release-drafter.yml@main
+    uses: netcracker/qubership-workflow-hub/.github/workflows/release-drafter.yml@v1.0.1
     with:
       version: ${{ needs.deploy.outputs.release-version }}
       publish: true
